name: Build docs
on:
  push:
    branches:
      - main
  pull_request:
env:
  POETRY_HOME: /opt/poetry
  POETRY_VERSION: 1.4.2
jobs:
  build:
    name: Build docs
    runs-on: ubuntu-20.04
    timeout-minutes: 15
    steps:
    - uses: actions/checkout@v2
      with:
        lfs: false
    - name: Checkout submodules
      shell: bash
      run: |
        GIT_LFS_SKIP_SMUDGE=1 git submodule update --init -- references/akari_software
    - uses: actions/setup-python@v4
      with:
        python-version: '3.8'
    - name: Set up venv
      run: |
        python3 -m venv venv
        . venv/bin/activate
    - name: Install Python dependencies
      run: |
        pip install -r requirements.txt
    - name: Get multi language text
      run: |
        make gettext
    - name: Build documents
      run: |
        sphinx-intl update -p _build/gettext -l ch -l en
        sphinx-build . _build/ja -D language='ja'
        sphinx-build . _build/en -D language='en'
        sphinx-build . _build/ch -D language='ch'
    - name: Deploy documents
      shell: bash
      if: github.ref == 'refs/heads/main'
      run: |
        tempdir=$(mktemp -d)

        cp -r _build/html $tempdir
        cd $tempdir/html
        touch .nojekyll

        git init
        git config user.name "Akari Group"
        git config user.email "akari.tmc@gmail.com"

        git checkout -B gh-pages
        git add .
        git commit -am "Build: $(date)"

        git remote add origin "https://git:${{ github.token }}@github.com/${{ github.repository }}"
        git push -f origin HEAD
